---
include:
  - board: nice_nano_v2
    shield: super_ergo_test_left
    cmake-args: -DCONFIG_ZMK_BLE=y
    artifact-name: super_ergo_left
  - board: nice_nano_v2
    shield: super_ergo_test_right
    cmake-args: -DCONFIG_ZMK_BLE=y
    artifact-name: super_ergo_right
